name: Deploy

on:
  push:
     branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true # Checkout private submodules(themes or something else).
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '7.10.0'
    
    - name: Install Dependencies
      run: npm install
      
    - name: Hexo g
      run: hexo g
      
    - name: Show pwd
      run: ls /home/runner/work/Demired.github.io/Demired.github.io
      
    - name: Show pwd
      run: ls /home/runner/work/Demired.github.io/public
    
    

   
