name: Deploy

on:
  push:
     branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    
    - name: Configuration environment
      env:
          HEXO_DEPLOY_PRI: ${{secrets.DEPLOY_KEY}}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name "zhangyuan"
        git config --global user.email "zhangyuan@newyou.ltd"
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '7.10.0'
      
    - name: Install Hexo
      run: |
        npm install -g hexo@3.2.2
        
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true # Checkout private submodules(themes or something else).
        
    - name: Hexo build
      run: |
        ls -la
        hexo g -d
    
    - name: Commit files
      run: |
        ls -la
        git checkout --orphan temporary
        ls -la
        git reset
        git add public -f
        git commit -m 'new branch'
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        force: true

        

    
  

   
