name: Deploy

on:
  push:
     branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true # Checkout private submodules(themes or something else).
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '7.10.0'
    
    - name: Install Dependencies
      run: npm install
      
    - name: Deploy
      id: deploy
      uses: sma11black/hexo-action@v1.0.3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        user_name: zhangyuan
        user_email: zhangyuan@newyou.ltd
      
    - name: Show pwd
      run:  cd /home/runner/work/Demired.github.io/Demired.github.io/public&&git init&&git config user.name "zhangyuan"&&git config user.email "zhangyuan@newyou.ltd"&&git add .&&git commit -m "Update docs"&&git push --force --quiet "git@github.com:Demired/Demired.github.io.git" master:gh-pages
      

    
    

   
